name: build-image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        docker build /home/docker/actions-runner/_work/self-hosted-runner --network host --tag self-hosted-runner